# Generated by Django 5.1.7 on 2025-04-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_manufacturer_alter_driver_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="manufacturer",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
