# Generated by Django 5.1.7 on 2025-04-01 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_alter_car_manufacturer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="taxi.manufacturer"
            ),
        ),
    ]
